name: echalk
description: "The Crossfit WOD app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  intl: any
  logging: ^1.2.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  freezed: ^2.4.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
